### PR TITLE
Select..For Update - Oracle Specific Query building and function name conversion

### PR DESCRIPTION
**Pull request by SimonH**
Hi Frank,

   I updated to 0.17.0.1 so that I could use some changes I'd asked Mark to include in the core libraries. 

   I haven't update the nuspec files for the solution as I figured you'd want to make sure all was OK before you altered them and published a new version.

   The changes supply an ICustomQueryBuilder (similar to ICustomInserter) which allows more Oracle specific queries and in my case allows the SimpleQuery.ForUpdate() function to build SELECT....FOR UPDATE. 
   At the same time I was able to change it so that we can use an Oracle specific IFunctionNameConverter to allow for differences between Sql Server and Oracle (e.g. Sql Len => Oracle Length).
  I added Unit tests for the new functionality and ran (as much as possible) against my Oracle 11g Xe install

Thanks

Simon

### CODE REVIEW

**Comment by flq** [comment]
Greetings Simon,
nowadays, since I switched work, I have no contact whatsoever to Oracle DBs, and with new hardware I dont even have the means to test the code, so I am actually looking for a new maintainer...

**Comment by SimonH** [comment]
Hi Frank,

```
 Wow! I've only ever contributed to projects, so I'm not sure 
```

exactly how much is involved in maintaining them. Also, I don't think 
I've ever managed to run all of the tests.
     Let me take a look at it over the weekend and I'll let you know how 
I get on next week.

Thanks,

Simon

**Comment by SimonH** [comment]
Hi Frank,

I've sat down this evening and made the changes so that the current unit tests in Simple.Data.Oracle now pass against my Oracle 11g XE database. I also added the alterations required to the hr schema into the readme.md file so it should be easier for others to get them up and running in the future.

I'm not quite sure what taking over as maintainer entails but I'm happy to give it a go. Is it simply using my fork on GitHub instead of yours and changing the details in the nuget package? If it is then I'll change the details and publish a new package later this week.

Good luck with the new role,

Thanks,

Simon

Slimtech IT Consultants Limited 

38, Driftway Road, Hook, Hampshire RG27 9SB

Registered in England and Wales No. 07339148

**Comment by flq** [comment]
Greetings Simon,
that sounds awesome! 

What it entails to be a maintainer is probably a good question :) From my personal viewpoint I think it would be to make sure the package isn't left behind with regard to Simple.Data itself, checking out any pull requests that come from other people and incorporating them if possible, and finally updating the Nuget on the official feed :) Maybe it sounds a lot, but it doesn't have to be.

Yes, we could say that your fork simply becomes the "main" repository, we can express that by changing the Nuget package's project site to point to your project location. If you have a Nuget account I can add you to the list of people that are allowed to update the package, that way there is no break in the Nuget history.

You can certainly contact me if you think it can be helpful and it doesn't include firing up an ORCL DB :)

Cheers
FQ

**Comment by SimonH** [comment]
Hi Frank, 

That all sounds good. I have a login for Nuget the email is the same simon@slimtech-it.co.uk. I don't actually have anything else setup on my profile but I can also login with simon@slimtech-it, so I'm guessing that's all you need to allow me to update the package.

Once you've added me I'll go through the process of changing the details and uploading a new package. I'm sure it will be fine but I'll definitely ask if I need anything,

Thanks again,

Simon

Slimtech IT Consultants Limited 

38, Driftway Road, Hook, Hampshire RG27 9SB

Registered in England and Wales No. 07339148

**Comment by flq** [comment]
Hi Simon,
the email won't be accepted as username. When you log into Nuget, check out what username is shown on the upper-right corner (e,g, mine says flq), then I'll try that one.

**Comment by SimonH** [comment]
Hi Frank,

It's never easy is it?

That would be simon@slimtech-it I guess. That's what it says on the link to my account.

Thanks,

Simon

-----Original Message-----

**Comment by flq** [comment]
Ha, OK, now it was accepted. It says pending approval, so you should get some notification. Do you have a twitter handle? I'd just like to let Mark Rendle know :)

**Comment by SimonH** [comment]
Hi Frank,

```
 I've accepted. I'll probably try and update the package tomorrow 
```

night as tonight I have some other stuff to sort out.

Unfortunately, I don't have a twitter handle and, to be honest, it's 
unlikely that I'll be getting one anytime soon :-)

Thanks,

Simon

**Pull request closed without merging**
